//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzueva_Ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksCatalog
    {
        public int ID { get; set; }
        public string Titile { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Writer { get; set; }
        public Nullable<int> NumberMagazine { get; set; }
        public Nullable<int> NumberStok { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genre Genre1 { get; set; }
    }
}
