//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buzueva_Ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<System.DateTime> Reserv { get; set; }
    }
}
